# Generated by Django 3.0.4 on 2020-04-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=200)),
                ('fl_oz', models.DecimalField(decimal_places=2, max_digits=7)),
                ('g_sugar', models.DecimalField(decimal_places=2, max_digits=7)),
                ('g_floz', models.DecimalField(decimal_places=2, max_digits=7)),
                ('mg_caffeine', models.PositiveIntegerField()),
                ('mg_floz', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
