# Generated by Django 3.0.4 on 2020-04-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200409_0508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='drinks',
        ),
    ]
