# Generated by Django 3.0.4 on 2020-05-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200409_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caffeine',
            fields=[
                ('drink_name', models.CharField(blank=True, max_length=30, null=True)),
                ('fl_oz', models.FloatField(blank=True, null=True)),
                ('mg_caffeine', models.FloatField(blank=True, null=True)),
                ('mg_floz', models.FloatField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'caffeine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sugar',
            fields=[
                ('drink_name', models.CharField(blank=True, max_length=30, null=True)),
                ('fl_oz', models.FloatField(blank=True, null=True)),
                ('g_sugar', models.FloatField(blank=True, null=True)),
                ('g_floz', models.FloatField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sugar',
                'managed': False,
            },
        ),
    ]
