# Generated by Django 3.0.4 on 2020-04-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_drinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(blank=True, max_length=30, null=True)),
                ('fl_oz', models.FloatField(blank=True, null=True)),
                ('g_sugar', models.FloatField(blank=True, null=True)),
                ('g_floz', models.FloatField(blank=True, null=True)),
                ('mg_caffeine', models.FloatField(blank=True, null=True)),
                ('mg_floz', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Drink',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Drinks',
        ),
    ]
